# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(577, 252)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputValidaCpf = QtWidgets.QLineEdit(self.centralwidget)
        self.inputValidaCpf.setGeometry(QtCore.QRect(138, 9, 291, 52))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.inputValidaCpf.setFont(font)
        self.inputValidaCpf.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    \n"
"}\n"
"")
        self.inputValidaCpf.setObjectName("inputValidaCpf")
        self.btnGeraCpf = QtWidgets.QPushButton(self.centralwidget)
        self.btnGeraCpf.setGeometry(QtCore.QRect(440, 70, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnGeraCpf.setFont(font)
        self.btnGeraCpf.setStyleSheet("border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"")
        self.btnGeraCpf.setObjectName("btnGeraCpf")
        self.labelRetorno = QtWidgets.QLabel(self.centralwidget)
        self.labelRetorno.setGeometry(QtCore.QRect(10, 150, 460, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(45)
        font.setBold(False)
        font.setWeight(50)
        self.labelRetorno.setFont(font)
        self.labelRetorno.setStyleSheet("color: #FFA500;")
        self.labelRetorno.setText("")
        self.labelRetorno.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRetorno.setObjectName("labelRetorno")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 107, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnValidaCpf = QtWidgets.QPushButton(self.centralwidget)
        self.btnValidaCpf.setGeometry(QtCore.QRect(440, 10, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnValidaCpf.setFont(font)
        self.btnValidaCpf.setStyleSheet("border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"")
        self.btnValidaCpf.setObjectName("btnValidaCpf")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 90, 119, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Valida CPF"))
        self.btnGeraCpf.setText(_translate("MainWindow", "GERAR"))
        self.label.setText(_translate("MainWindow", "Valida CPF"))
        self.btnValidaCpf.setText(_translate("MainWindow", "Validar"))
        self.label_2.setText(_translate("MainWindow", "Gera CPF >>>"))
